### PR TITLE
ic-ref-run: Execute heartbeats before any submitted message

### PR DESCRIPTION
**Pull request by mraszyk**
Follow-up on #69

### CODE REVIEW

**Comment by ggreif** [comment]
Will this place the canister callback invocations nearer to the scheduled expiration date?

**Comment by mraszyk** [comment]
> Will this place the canister callback invocations nearer to the scheduled expiration date?

I didn't quite get the question. The change would make heartbeats and timers more deterministic by triggering them if new calls are submitted.

**Comment by ggreif** [comment]
> > Will this place the canister callback invocations nearer to the scheduled expiration date?
> 
> I didn't quite get the question. The change would make heartbeats and timers more deterministic by triggering them if new calls are submitted.

Yeah, this answers my question.

**Comment by mraszyk** [comment]
@ggreif Could you please make sure this MR does not break your tests and approve if it works?

**Comment by ggreif** [comment]
I don't see much of a difference. The tests give the same results. I think that is a good sign.

**Review by ggreif — APPROVED** [review]
Looks like a sensible thing to do.

**Pull request merged**
