### PR TITLE
Bump Candid to version 0.2

### PR DESCRIPTION
**Pull request by nomeata**

### CODE REVIEW

**Comment by nomeata** [comment]
@basvandijk, FYI, this includes your changes to candid as needed for #19.

**Comment by nomeata** [comment]
Looks like I am no longer committer or admin in this repo, so I can't merge this. If you appreciate my help with this project, can you add me again?

**Comment by nomeata** [comment]
Ping? :-)

**Comment by ggreif** [comment]
I've just  seen this 👀

**Review by ggreif — APPROVED** [review]
LGTM!

**Comment by ggreif** [comment]
I have merged this, unfortunately I have no _Settings_ tab in the main page, so I can't grant commit access to Joachim. @basvandijk @ielashi @jwiegley, if you have such access, please add him.

**Pull request merged**
