### PR TITLE
chore: bump `nixpkgs` to 22.11 branch

### PR DESCRIPTION
**Pull request by ggreif**
the specific revisions here are pinned in a way that helps to seed the binary cache (for use of `dfinity/motoko`)

### CODE REVIEW

**Comment by nomeata** [comment]
I don't recognize the failure. Maybe @basvandijk can advise.

**Comment by basvandijk** [comment]
@mraszyk and I were also hitting that `error: unexpected end-of-file` when installing `nix-build-uncached` [before](https://github.com/dfinity/ic-hs/actions/runs/4073393510/jobs/7037090534). 

I'm also hitting it in the `farm` repo. 

I'll email the nixbuild.net folks to see if they know what's going on. Will CC you guys.

**Comment by ggreif** [comment]
Looks like there is a problem with Python:
```
error: builder for '/nix/store/2hcsszvp6vz7ayy6j5pl22zfh04im1z6-python3.10-httpbin-0.7.0.drv' failed with exit code 1;
[1753](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1754)
       last 10 log lines:
[1754](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1755)
       > INFO: pip is looking at multiple versions of itsdangerous to determine which version is compatible with other requirements. This could take a while.
[1755](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1756)
       > INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
[1756](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1757)
       > INFO: pip is looking at multiple versions of decorator to determine which version is compatible with other requirements. This could take a while.
[1757](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1758)
       > INFO: pip is looking at multiple versions of brotlipy to determine which version is compatible with other requirements. This could take a while.
[1758](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1759)
       > INFO: pip is looking at multiple versions of markupsafe to determine which version is compatible with other requirements. This could take a while.
[1759](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1760)
       > INFO: pip is looking at multiple versions of werkzeug to determine which version is compatible with other requirements. This could take a while.
[1760](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1761)
       > INFO: pip is looking at multiple versions of httpbin to determine which version is compatible with other requirements. This could take a while.
[1761](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1762)
       > ERROR: Could not find a version that satisfies the requirement blinker>=1.1; extra == "flask" (from raven[flask]) (from versions: none)
[1762](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1763)
       > ERROR: No matching distribution found for blinker>=1.1; extra == "flask"
[1763](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1764)
       > 
[1764](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1765)
       For full logs, run 'nix log /nix/store/2hcsszvp6vz7ayy6j5pl22zfh04im1z6-python3.10-httpbin-0.7.0.drv'.
[1765](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1766)
error: 
[1766](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1767)
nix-build-uncached: nix build failed: exit status 1
[1767](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1768)

[1768](https://github.com/dfinity/ic-hs/actions/runs/4086214496/jobs/7045223904#step:12:1769)
Error: Process completed with exit code 1.
```
This is on the Mac, but I expect it to happen on Ubuntu too.

**Comment by mraszyk** [comment]
I have bumped nixpkgs to current master to have a recent version of rustc for the universal canister in another MR #138

**Comment by mraszyk** [comment]
Covered by #138

**Pull request closed without merging**
